### ISSUE TITLE
Checkbox state

### ISSUE THREAD

**Issue by sweenzor** [bshannon/savenotes#1]
Continuing our conversation from ydkhatri/mac_apt/issues/13:

I've gotten it up and running. Super exciting! Thanks for the hard work!

When I'm using either the `-m` or `-h` args, I get checklist items decorated with the following html:
```<div style="103">```

Regardless of whether or not the checkbox is checked.

**Comment by bshannon** [comment]
Ya, there's a bunch of stuff I haven't tried to handle yet.  (Mostly haven't had time to get back to this.)

How do you think a checklist item should be formatted in html or markdown?

**Comment by sweenzor** [comment]
I would think markdown. I find this notation pretty reasonable:

https://github.github.com/gfm/#task-list-items-extension-

**Comment by sweenzor** [comment]
(But I can deal with any way of indicating checkbox state)

**Comment by sweenzor** [comment]
I just noticed something. When you copy and paste a checklist out of notes, the resulting text follows the GFM convention:

```
- [ ] Unchecked item
- [x] Checked item
```

**Comment by bshannon** [comment]
Just to let you know I haven't forgotten about this...

I started working on this, but it's not as straightforward as I was hoping.
I'm having to do more significant work than expected to get all but the
most trivial cases to work correctly.

**Comment by sweenzor** [comment]
Ah, bummer. I appreciate the effort!

**Comment by bshannon** [comment]
I think I've got it working now.  Try the 1.1 release.

**Comment by sweenzor** [comment]
Oh awesome! I’ll give it a try!

**Comment by sweenzor** [comment]
Working! Thank you!!
