### ISSUE TITLE
Instructions to compile?

### ISSUE THREAD

**Issue by t5n** [bshannon/savenotes#2]
Any chance you can provide instructions for getting this up and running? I just installed JDK and have no idea what to do next.
Thanks!

**Comment by bshannon** [comment]
I was hoping to make more progress on this this weekend, but then my laptop died.
I've published a [1.0 release](https://github.com/bshannon/savenotes/releases/tag/1.0) to make it easier to get started so you won't need to build it yourself.
If you really want to build it, you'll need Apache Maven.
